name: smalldogbig
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - scikit-image=0.19.2
  - tqdm=4.64.0
  - pip:
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - timm==0.6.7
    - addict=2.4.0
    - future=0.18.2
    - lmdb=1.3.0
    - pyyaml=6.0
    - requests=2.28.1
    - tb-nightly=2.11.0
    - yapf=0.32.0
    - lpips=0.1.4
    - gdown=4.5.1
